line-length = 88
indent-width = 4

[lint]
preview = true

[format]
# Docstring formatting is opt-in. Enable it by setting this option to `true`.
#docstring-code-format = true
#docstring-code-line-length = 40

preview = true
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
